enum AiProblemIntent {
  scientificCalculation,
  graphing,
  matrix,
  equationSolving,
  calculus,
  statistics,
  finance,
  linearProgramming,
  integerProgramming,
  operationsResearch,
  formulaLookup,
  unsupported,
  outOfScope,
}
