import 'package:calcademy/app/tools/calcademy_tool_registry.dart';
import 'package:calcademy/features/formula_library/domain/formula_category.dart';
import 'package:calcademy/features/formula_library/domain/formula_entry.dart';
import 'package:calcademy/features/formula_library/domain/formula_example.dart';
import 'package:calcademy/features/formula_library/domain/formula_tool_link.dart';
import 'package:calcademy/features/formula_library/domain/formula_variable.dart';

abstract final class FormulaRegistry {
  static final List<FormulaEntry> entries = List.unmodifiable(_entries);
  static final Map<String, FormulaEntry> _byId = {
    for (final entry in entries) entry.id: entry,
  };

  static FormulaEntry? byId(String id) => _byId[id];

  static List<FormulaEntry> search({
    String query = '',
    FormulaCategory? category,
    String languageCode = 'en',
  }) {
    final needle = query.trim().toLowerCase();
    return entries
        .where((entry) {
          if (category != null && entry.category != category) return false;
          if (needle.isEmpty) return true;
          final haystack = [
            entry.titleEn,
            entry.titleTr,
            entry.descriptionEn,
            entry.descriptionTr,
            entry.plainTextFormula,
            entry.category.titleEn,
            entry.category.titleTr,
            ...entry.tags,
            ...entry.variables.expand(
              (item) => [item.symbol, item.nameEn, item.nameTr],
            ),
          ].join(' ').toLowerCase();
          return haystack.contains(needle);
        })
        .toList(growable: false);
  }
}

final List<FormulaEntry> _entries = [
  _f(
    'quadratic-formula',
    'Quadratic Formula',
    'İkinci Derece Denklem Formülü',
    FormulaCategory.algebra,
    'x = (-b ± √(b² - 4ac)) / 2a',
    'Finds the roots of a quadratic equation.',
    'İkinci dereceden bir denklemin köklerini bulur.',
    [
      'a|quadratic coefficient|ikinci derece katsayısı',
      'b|linear coefficient|birinci derece katsayısı',
      'c|constant term|sabit terim',
    ],
    'a=1, b=-3, c=2',
    'x = 1 or 2',
    'equation_solver',
    'roots,kökler,polynomial,polinom',
  ),
  _f(
    'distance-formula',
    'Distance Formula',
    'Uzaklık Formülü',
    FormulaCategory.mathematics,
    'd = √((x₂-x₁)² + (y₂-y₁)²)',
    'Measures the distance between two Cartesian points.',
    'İki Kartezyen nokta arasındaki uzaklığı ölçer.',
    [
      'd|distance|uzaklık',
      'x₁,x₂|x coordinates|x koordinatları',
      'y₁,y₂|y coordinates|y koordinatları',
    ],
    '(0,0), (3,4)',
    'd = 5',
    'scientific_calculator',
    'geometry,geometri,point,nokta',
  ),
  _f(
    'slope',
    'Slope',
    'Eğim',
    FormulaCategory.algebra,
    'm = (y₂-y₁) / (x₂-x₁)',
    'Calculates the rate of change between two points.',
    'İki nokta arasındaki değişim oranını hesaplar.',
    [
      'm|slope|eğim',
      'x₁,x₂|x coordinates|x koordinatları',
      'y₁,y₂|y coordinates|y koordinatları',
    ],
    '(1,2), (3,6)',
    'm = 2',
    'graph_plotter',
    'line,doğru,rate,oran',
  ),
  _f(
    'arithmetic-sequence',
    'Arithmetic Sequence',
    'Aritmetik Dizi',
    FormulaCategory.algebra,
    'aₙ = a₁ + (n-1)d',
    'Finds a term of a sequence with constant difference.',
    'Sabit farkı olan bir dizinin terimini bulur.',
    [
      'aₙ|nth term|n. terim',
      'a₁|first term|ilk terim',
      'd|common difference|ortak fark',
      'n|term index|terim sırası',
    ],
    'a₁=2, d=3, n=5',
    'a₅ = 14',
    'scientific_calculator',
    'sequence,dizi,series,seri',
  ),
  _f(
    'geometric-sequence',
    'Geometric Sequence',
    'Geometrik Dizi',
    FormulaCategory.algebra,
    'aₙ = a₁rⁿ⁻¹',
    'Finds a term of a sequence with constant ratio.',
    'Sabit oranı olan bir dizinin terimini bulur.',
    [
      'aₙ|nth term|n. terim',
      'a₁|first term|ilk terim',
      'r|common ratio|ortak oran',
      'n|term index|terim sırası',
    ],
    'a₁=3, r=2, n=4',
    'a₄ = 24',
    'scientific_calculator',
    'sequence,dizi,ratio,oran',
  ),
  _f(
    'logarithm-product-rule',
    'Logarithm Product Rule',
    'Logaritma Çarpım Kuralı',
    FormulaCategory.algebra,
    'log_b(xy) = log_b(x) + log_b(y)',
    'Expands the logarithm of a product.',
    'Bir çarpımın logaritmasını toplam biçiminde açar.',
    ['b|base|taban', 'x,y|positive factors|pozitif çarpanlar'],
    'b=10, x=10, y=100',
    'log₁₀(1000) = 3',
    'scientific_calculator',
    'logarithm,logaritma,product,çarpım',
  ),
  _f(
    'exponent-product-rule',
    'Exponent Product Rule',
    'Üslü İfade Çarpım Kuralı',
    FormulaCategory.algebra,
    'aᵐaⁿ = aᵐ⁺ⁿ',
    'Combines powers that have the same base.',
    'Aynı tabanlı kuvvetleri birleştirir.',
    ['a|base|taban', 'm,n|exponents|üsler'],
    'a=2, m=3, n=4',
    '2³·2⁴ = 2⁷ = 128',
    'scientific_calculator',
    'exponent,üs,power,kuvvet',
  ),

  _f(
    'power-rule-derivative',
    'Power Rule Derivative',
    'Türev Kuvvet Kuralı',
    FormulaCategory.calculus,
    'd/dx(xⁿ) = nxⁿ⁻¹',
    'Differentiates a power of x.',
    'x değişkeninin bir kuvvetinin türevini alır.',
    ['x|variable|değişken', 'n|power|kuvvet'],
    'f(x)=x⁴',
    "f'(x)=4x³",
    'calculus',
    'derivative,türev,power,kuvvet',
  ),
  _f(
    'product-rule',
    'Product Rule',
    'Çarpım Kuralı',
    FormulaCategory.calculus,
    "(fg)' = f'g + fg'",
    'Differentiates a product of two functions.',
    'İki fonksiyonun çarpımının türevini alır.',
    ['f,g|functions|fonksiyonlar', "f',g'|derivatives|türevler"],
    'f=x², g=x+1',
    "(fg)'=3x²+2x",
    'calculus',
    'derivative,türev,product,çarpım',
  ),
  _f(
    'quotient-rule',
    'Quotient Rule',
    'Bölüm Kuralı',
    FormulaCategory.calculus,
    "(f/g)' = (f'g - fg') / g²",
    'Differentiates a quotient of two functions.',
    'İki fonksiyonun bölümünün türevini alır.',
    ['f,g|functions|fonksiyonlar', "f',g'|derivatives|türevler"],
    'f=x², g=x+1',
    "(f/g)'=(x²+2x)/(x+1)²",
    'calculus',
    'derivative,türev,quotient,bölüm',
  ),
  _f(
    'chain-rule',
    'Chain Rule',
    'Zincir Kuralı',
    FormulaCategory.calculus,
    "d/dx f(g(x)) = f'(g(x))g'(x)",
    'Differentiates a composite function.',
    'Bileşke bir fonksiyonun türevini alır.',
    ['f|outer function|dış fonksiyon', 'g|inner function|iç fonksiyon'],
    'f(u)=u², g(x)=3x+1',
    'd/dx(3x+1)² = 6(3x+1)',
    'calculus',
    'derivative,türev,composite,bileşke',
  ),
  _f(
    'definite-integral',
    'Definite Integral',
    'Belirli İntegral',
    FormulaCategory.calculus,
    '∫ₐᵇ f(x)dx = F(b)-F(a)',
    'Finds signed area using an antiderivative.',
    'Bir ters türevle işaretli alanı bulur.',
    [
      'f|integrand|integrand',
      'F|antiderivative|ters türev',
      'a,b|bounds|sınırlar',
    ],
    'f(x)=2x, a=0, b=3',
    '∫₀³2x dx = 9',
    'calculus',
    'integral,integral,area,alan',
  ),
  _f(
    'integration-power-rule',
    'Integration Power Rule',
    'İntegral Kuvvet Kuralı',
    FormulaCategory.calculus,
    '∫xⁿdx = xⁿ⁺¹/(n+1) + C, n≠-1',
    'Integrates a power of x.',
    'x değişkeninin bir kuvvetinin integralini alır.',
    [
      'x|variable|değişken',
      'n|power|kuvvet',
      'C|integration constant|integrasyon sabiti',
    ],
    'n=2',
    '∫x²dx = x³/3 + C',
    'calculus',
    'integral,antiderivative,ters türev',
  ),
  _f(
    'tangent-line',
    'Tangent Line',
    'Teğet Doğrusu',
    FormulaCategory.calculus,
    'y - f(a) = f′(a)(x-a)',
    'Builds the tangent line at x=a.',
    'x=a noktasındaki teğet doğrusunu kurar.',
    [
      'a|contact point|temas noktası',
      'f(a)|function value|fonksiyon değeri',
      'f′(a)|slope|eğim',
    ],
    'f(x)=x², a=1',
    'y=2x-1',
    'graph_plotter',
    'tangent,teğet,slope,eğim',
  ),

  _f(
    'determinant-2x2',
    '2×2 Determinant',
    '2×2 Determinant',
    FormulaCategory.linearAlgebra,
    'det(A) = ad - bc',
    'Computes the determinant of a 2×2 matrix.',
    '2×2 bir matrisin determinantını hesaplar.',
    ['a,b,c,d|matrix entries|matris elemanları'],
    'A=[[2,1],[3,4]]',
    'det(A)=5',
    'matrix',
    'matrix,matris,determinant',
  ),
  _f(
    'determinant-3x3',
    '3×3 Determinant',
    '3×3 Determinant',
    FormulaCategory.linearAlgebra,
    'det(A) = a(ei-fh)-b(di-fg)+c(dh-eg)',
    'Expands a 3×3 determinant along the first row.',
    '3×3 determinantı ilk satır boyunca açar.',
    ['a…i|matrix entries|matris elemanları'],
    'A=[[1,0,0],[0,2,0],[0,0,3]]',
    'det(A)=6',
    'matrix',
    'matrix,matris,determinant',
  ),
  _f(
    'matrix-dimension-rule',
    'Matrix Multiplication Dimension Rule',
    'Matris Çarpımı Boyut Kuralı',
    FormulaCategory.linearAlgebra,
    '(m×n)(n×p) → m×p',
    'States when matrix multiplication is defined.',
    'Matris çarpımının ne zaman tanımlı olduğunu belirtir.',
    ['m,n,p|dimensions|boyutlar'],
    '(2×3)(3×4)',
    'result dimension = 2×4',
    'matrix',
    'matrix,matris,dimension,boyut',
  ),
  _f(
    'inverse-2x2',
    'Inverse of a 2×2 Matrix',
    '2×2 Matrisin Tersi',
    FormulaCategory.linearAlgebra,
    'A⁻¹ = 1/(ad-bc) [[d,-b],[-c,a]]',
    'Finds the inverse when the determinant is nonzero.',
    'Determinant sıfır değilken matrisin tersini bulur.',
    ['a,b,c,d|matrix entries|matris elemanları'],
    'A=[[2,1],[1,1]]',
    'A⁻¹=[[1,-1],[-1,2]]',
    'matrix',
    'matrix,matris,inverse,ters',
  ),
  _f(
    'cramers-rule',
    "Cramer's Rule",
    'Cramer Kuralı',
    FormulaCategory.linearAlgebra,
    'xᵢ = det(Aᵢ) / det(A)',
    'Solves a square linear system with determinants.',
    'Kare bir doğrusal sistemi determinantlarla çözer.',
    [
      'A|coefficient matrix|katsayı matrisi',
      'Aᵢ|replaced-column matrix|sütunu değiştirilmiş matris',
    ],
    '2x+y=5, x-y=1',
    'x=2, y=1',
    'matrix',
    'linear system,lineer sistem,determinant',
  ),
  _f(
    'dot-product',
    'Dot Product',
    'İç Çarpım',
    FormulaCategory.linearAlgebra,
    'a·b = Σaᵢbᵢ',
    'Measures directional alignment of two vectors.',
    'İki vektörün yönsel uyumunu ölçer.',
    ['a,b|vectors|vektörler'],
    'a=(1,2), b=(3,4)',
    'a·b=11',
    'matrix',
    'vector,vektör,dot product,iç çarpım',
  ),
  _f(
    'vector-magnitude',
    'Vector Magnitude',
    'Vektör Büyüklüğü',
    FormulaCategory.linearAlgebra,
    '||v|| = √(Σvᵢ²)',
    'Computes the Euclidean length of a vector.',
    'Bir vektörün Öklid uzunluğunu hesaplar.',
    ['v|vector|vektör'],
    'v=(3,4)',
    '||v||=5',
    'matrix',
    'vector,vektör,norm,büyüklük',
  ),

  _f(
    'arithmetic-mean',
    'Arithmetic Mean',
    'Aritmetik Ortalama',
    FormulaCategory.statisticsProbability,
    'x̄ = Σxᵢ/n',
    'Computes the average of observations.',
    'Gözlemlerin ortalamasını hesaplar.',
    ['xᵢ|observations|gözlemler', 'n|count|sayı'],
    '2,4,6',
    'x̄=4',
    'statistics',
    'mean,average,ortalama',
  ),
  _f(
    'weighted-mean',
    'Weighted Mean',
    'Ağırlıklı Ortalama',
    FormulaCategory.statisticsProbability,
    'x̄w = Σwᵢxᵢ / Σwᵢ',
    'Computes an average with observation weights.',
    'Gözlem ağırlıklarıyla ortalama hesaplar.',
    ['xᵢ|observations|gözlemler', 'wᵢ|weights|ağırlıklar'],
    'x=(70,90), w=(1,3)',
    'x̄w=85',
    'statistics',
    'weighted,ağırlıklı,mean,ortalama',
  ),
  _f(
    'population-variance',
    'Population Variance',
    'Anakütle Varyansı',
    FormulaCategory.statisticsProbability,
    'σ² = Σ(xᵢ-μ)²/N',
    'Measures population dispersion around the mean.',
    'Anakütlenin ortalama çevresindeki yayılımını ölçer.',
    [
      'xᵢ|observations|gözlemler',
      'μ|population mean|anakütle ortalaması',
      'N|population size|anakütle büyüklüğü',
    ],
    '1,2,3',
    'σ²=2/3',
    'statistics',
    'variance,varyans,dispersion,yayılım',
  ),
  _f(
    'standard-deviation',
    'Standard Deviation',
    'Standart Sapma',
    FormulaCategory.statisticsProbability,
    'σ = √σ²',
    'Expresses dispersion in the original unit.',
    'Yayılımı özgün birimde ifade eder.',
    ['σ²|variance|varyans', 'σ|standard deviation|standart sapma'],
    'σ²=9',
    'σ=3',
    'statistics',
    'standard deviation,standart sapma',
  ),
  _f(
    'z-score',
    'Z-score',
    'Z-skoru',
    FormulaCategory.statisticsProbability,
    'z = (x-μ)/σ',
    'Standardizes a value relative to a mean and deviation.',
    'Bir değeri ortalama ve sapmaya göre standartlaştırır.',
    ['x|value|değer', 'μ|mean|ortalama', 'σ|standard deviation|standart sapma'],
    'x=85, μ=70, σ=10',
    'z=1.5',
    'statistics',
    'z score,z skoru,standardize',
  ),
  _f(
    'normal-standardization',
    'Normal Distribution Standardization',
    'Normal Dağılım Standardizasyonu',
    FormulaCategory.statisticsProbability,
    'Z = (X-μ)/σ ~ N(0,1)',
    'Transforms a normal variable to the standard normal scale.',
    'Normal bir değişkeni standart normal ölçeğe dönüştürür.',
    [
      'X|normal variable|normal değişken',
      'μ|mean|ortalama',
      'σ|standard deviation|standart sapma',
    ],
    'X=110, μ=100, σ=5',
    'Z=2',
    'statistics',
    'normal distribution,normal dağılım',
  ),
  _f(
    'binomial-probability',
    'Binomial Probability',
    'Binom Olasılığı',
    FormulaCategory.statisticsProbability,
    'P(X=k)=C(n,k)pᵏ(1-p)ⁿ⁻ᵏ',
    'Finds exactly k successes in n independent trials.',
    'n bağımsız denemede tam k başarı olasılığını bulur.',
    [
      'n|trials|deneme',
      'k|successes|başarı',
      'p|success probability|başarı olasılığı',
    ],
    'n=3, k=2, p=0.5',
    'P(X=2)=0.375',
    'statistics',
    'binomial,binom,probability,olasılık',
  ),
  _f(
    'poisson-probability',
    'Poisson Probability',
    'Poisson Olasılığı',
    FormulaCategory.statisticsProbability,
    'P(X=k)=e⁻λλᵏ/k!',
    'Models event counts at a constant average rate.',
    'Sabit ortalama hızdaki olay sayılarını modeller.',
    ['λ|average rate|ortalama hız', 'k|event count|olay sayısı'],
    'λ=2, k=0',
    'P(X=0)=e⁻²≈0.1353',
    'statistics',
    'poisson,probability,olasılık',
  ),
  _f(
    'confidence-interval-mean',
    'Confidence Interval for a Mean',
    'Ortalama İçin Güven Aralığı',
    FormulaCategory.statisticsProbability,
    'x̄ ± z*σ/√n',
    'Estimates a population mean with known deviation.',
    'Sapma biliniyorken anakütle ortalamasını tahmin eder.',
    [
      'x̄|sample mean|örneklem ortalaması',
      'z*|critical value|kritik değer',
      'σ|population deviation|anakütle sapması',
      'n|sample size|örneklem büyüklüğü',
    ],
    'x̄=50, z*=1.96, σ=10, n=100',
    '[48.04, 51.96]',
    'statistics',
    'confidence interval,güven aralığı,mean,ortalama',
  ),

  _f(
    'simple-interest',
    'Simple Interest',
    'Basit Faiz',
    FormulaCategory.finance,
    'I = Prt',
    'Calculates interest without compounding.',
    'Bileşiklendirme olmadan faizi hesaplar.',
    [
      'I|interest|faiz',
      'P|principal|anapara',
      'r|periodic rate|dönemsel oran',
      't|time|süre',
    ],
    'P=1000, r=0.10, t=2',
    'I=200',
    'financial_calculator',
    'interest,faiz,simple,basit',
  ),
  _f(
    'compound-interest',
    'Compound Interest',
    'Bileşik Faiz',
    FormulaCategory.finance,
    'A = P(1+r/n)ⁿᵗ',
    'Accumulates principal with periodic compounding.',
    'Anaparayı dönemsel bileşik faizle büyütür.',
    [
      'A|accumulated amount|birikmiş tutar',
      'P|principal|anapara',
      'r|annual rate|yıllık oran',
      'n|compounds per year|yıllık dönem sayısı',
      't|years|yıl',
    ],
    'P=1000, r=0.10, n=1, t=2',
    'A=1210',
    'financial_calculator',
    'interest,faiz,compound,bileşik',
  ),
  _f(
    'present-value',
    'Present Value',
    'Bugünkü Değer',
    FormulaCategory.finance,
    'P = F/(1+i)ⁿ',
    'Discounts a future amount to today.',
    'Gelecekteki bir tutarı bugüne indirger.',
    [
      'P|present value|bugünkü değer',
      'F|future value|gelecek değer',
      'i|periodic rate|dönemsel oran',
      'n|periods|dönem',
    ],
    'F=1210, i=0.10, n=2',
    'P=1000',
    'financial_calculator',
    'present value,bugünkü değer,discount,iskonto',
  ),
  _f(
    'future-value',
    'Future Value',
    'Gelecek Değer',
    FormulaCategory.finance,
    'F = P(1+i)ⁿ',
    'Compounds a present amount into the future.',
    'Bugünkü bir tutarı geleceğe bileşik olarak taşır.',
    [
      'F|future value|gelecek değer',
      'P|present value|bugünkü değer',
      'i|periodic rate|dönemsel oran',
      'n|periods|dönem',
    ],
    'P=1000, i=0.10, n=2',
    'F=1210',
    'financial_calculator',
    'future value,gelecek değer,compound,bileşik',
  ),
  _f(
    'net-present-value',
    'Net Present Value',
    'Net Bugünkü Değer',
    FormulaCategory.finance,
    'NPV = -C₀ + Σ Cₜ/(1+r)ᵗ',
    'Discounts project cash flows and subtracts initial cost.',
    'Proje nakit akışlarını indirger ve başlangıç maliyetini çıkarır.',
    [
      'C₀|initial cost|başlangıç maliyeti',
      'Cₜ|cash flow|nakit akışı',
      'r|discount rate|iskonto oranı',
      't|period|dönem',
    ],
    'C₀=100, C₁=110, r=0.10',
    'NPV=0',
    'financial_calculator',
    'NPV,NBD,cash flow,nakit akışı',
  ),
  _f(
    'internal-rate-return',
    'Internal Rate of Return',
    'İç Verim Oranı',
    FormulaCategory.finance,
    '0 = -C₀ + Σ Cₜ/(1+IRR)ᵗ',
    'Defines the discount rate that makes NPV zero.',
    'NBD’yi sıfır yapan iskonto oranını tanımlar.',
    [
      'C₀|initial cost|başlangıç maliyeti',
      'Cₜ|cash flow|nakit akışı',
      'IRR|internal rate|iç verim oranı',
    ],
    'C₀=100, C₁=110',
    'IRR=10%',
    'financial_calculator',
    'IRR,İVO,return,getiri',
  ),
  _f(
    'payback-period',
    'Payback Period',
    'Geri Ödeme Süresi',
    FormulaCategory.finance,
    'Payback = full years + unrecovered cost / next cash flow',
    'Estimates when cumulative cash flow recovers an investment.',
    'Kümülatif nakit akışının yatırımı ne zaman karşıladığını tahmin eder.',
    ['C₀|initial cost|başlangıç maliyeti', 'Cₜ|cash flows|nakit akışları'],
    'C₀=100, annual C=40',
    'Payback=2.5 years',
    'financial_calculator',
    'payback,geri ödeme,cash flow,nakit akışı',
  ),
  _f(
    'loan-payment',
    'Loan Payment Annuity',
    'Kredi Ödemesi Anüitesi',
    FormulaCategory.finance,
    'A = P i(1+i)ⁿ / ((1+i)ⁿ-1)',
    'Calculates an equal end-of-period loan payment.',
    'Eşit dönem sonu kredi ödemesini hesaplar.',
    [
      'A|payment|ödeme',
      'P|principal|anapara',
      'i|periodic rate|dönemsel oran',
      'n|payments|ödeme sayısı',
    ],
    'P=1000, i=0.10, n=2',
    'A≈576.19',
    'financial_calculator',
    'loan,kredi,annuity,anüite',
  ),

  _f(
    'pf-factor',
    'P/F Factor',
    'P/F Faktörü',
    FormulaCategory.engineeringEconomy,
    'P/F = (1+i)⁻ⁿ',
    'Converts one future amount to present worth.',
    'Tek bir gelecek tutarı bugünkü değere çevirir.',
    [
      'P|present worth|bugünkü değer',
      'F|future worth|gelecek değer',
      'i|rate|oran',
      'n|periods|dönem',
    ],
    'i=0.10, n=2',
    'P/F=0.82645',
    'financial_calculator',
    'factor,faktör,present worth,bugünkü değer',
  ),
  _f(
    'fp-factor',
    'F/P Factor',
    'F/P Faktörü',
    FormulaCategory.engineeringEconomy,
    'F/P = (1+i)ⁿ',
    'Converts present worth to one future amount.',
    'Bugünkü değeri tek bir gelecek tutara çevirir.',
    [
      'F|future worth|gelecek değer',
      'P|present worth|bugünkü değer',
      'i|rate|oran',
      'n|periods|dönem',
    ],
    'i=0.10, n=2',
    'F/P=1.21',
    'financial_calculator',
    'factor,faktör,future worth,gelecek değer',
  ),
  _f(
    'pa-factor',
    'P/A Factor',
    'P/A Faktörü',
    FormulaCategory.engineeringEconomy,
    'P/A = ((1+i)ⁿ-1)/(i(1+i)ⁿ)',
    'Finds present worth of a uniform series.',
    'Eşit serinin bugünkü değerini bulur.',
    [
      'P|present worth|bugünkü değer',
      'A|uniform amount|eşit tutar',
      'i|rate|oran',
      'n|periods|dönem',
    ],
    'i=0.10, n=2',
    'P/A≈1.7355',
    'financial_calculator',
    'annuity,anüite,factor,faktör',
  ),
  _f(
    'ap-factor',
    'A/P Factor',
    'A/P Faktörü',
    FormulaCategory.engineeringEconomy,
    'A/P = i(1+i)ⁿ/((1+i)ⁿ-1)',
    'Annualizes a present amount over n periods.',
    'Bugünkü tutarı n döneme eşit olarak yayar.',
    [
      'A|uniform amount|eşit tutar',
      'P|present worth|bugünkü değer',
      'i|rate|oran',
      'n|periods|dönem',
    ],
    'i=0.10, n=2',
    'A/P≈0.5762',
    'financial_calculator',
    'capital recovery,sermaye geri kazanımı',
  ),
  _f(
    'equivalent-annual-cost',
    'Equivalent Annual Cost',
    'Eşdeğer Yıllık Maliyet',
    FormulaCategory.engineeringEconomy,
    'EAC = NPV / P/A(i,n)',
    'Converts a cost present value to an annual equivalent.',
    'Maliyetin bugünkü değerini yıllık eşdeğere çevirir.',
    [
      'EAC|annual cost|yıllık maliyet',
      'NPV|cost present value|maliyet bugünkü değeri',
      'P/A|annuity factor|anüite faktörü',
    ],
    'NPV=1735.54, P/A=1.73554',
    'EAC=1000/year',
    'financial_calculator',
    'annual cost,yıllık maliyet,equivalent,eşdeğer',
  ),
  _f(
    'benefit-cost-ratio',
    'Benefit–Cost Ratio',
    'Fayda–Maliyet Oranı',
    FormulaCategory.engineeringEconomy,
    'B/C = PW(benefits) / PW(costs)',
    'Compares discounted benefits with discounted costs.',
    'İndirgenmiş faydaları indirgenmiş maliyetlerle karşılaştırır.',
    [
      'B|benefit present worth|fayda bugünkü değeri',
      'C|cost present worth|maliyet bugünkü değeri',
    ],
    'B=120, C=100',
    'B/C=1.2',
    'financial_calculator',
    'benefit cost,fayda maliyet,ratio,oran',
  ),

  _f(
    'lp-objective',
    'Linear Programming Objective',
    'Doğrusal Programlama Amaç Fonksiyonu',
    FormulaCategory.optimization,
    'max/min z = Σcⱼxⱼ',
    'Defines a linear objective over decision variables.',
    'Karar değişkenleri üzerinde doğrusal bir amaç tanımlar.',
    [
      'z|objective value|amaç değeri',
      'cⱼ|objective coefficients|amaç katsayıları',
      'xⱼ|decision variables|karar değişkenleri',
    ],
    'max z=3x+2y',
    'at x=2,y=1: z=8',
    'linear_programming',
    'LP,DP,objective,amaç',
  ),
  _f(
    'constraint-standard-form',
    'Constraint Standard Form',
    'Kısıt Standart Formu',
    FormulaCategory.optimization,
    'Ax = b, x ≥ 0',
    'Expresses linear constraints in equality form.',
    'Doğrusal kısıtları eşitlik biçiminde ifade eder.',
    [
      'A|coefficient matrix|katsayı matrisi',
      'x|decision vector|karar vektörü',
      'b|right-hand side|sağ taraf',
    ],
    'x+y≤4',
    'x+y+s=4, s≥0',
    'linear_programming',
    'constraint,kısıt,standard form,standart form',
  ),
  _f(
    'transportation-balance',
    'Transportation Balance Condition',
    'Taşıma Denge Koşulu',
    FormulaCategory.operationsResearch,
    'Σ supply = Σ demand',
    'Checks whether total supply equals total demand.',
    'Toplam arzın toplam talebe eşit olup olmadığını denetler.',
    ['sᵢ|supplies|arzlar', 'dⱼ|demands|talepler'],
    'supply=30+20, demand=10+40',
    '50=50, balanced',
    'operations_research',
    'transportation,taşıma,supply,arz,demand,talep',
  ),
  _f(
    'assignment-objective',
    'Assignment Problem Objective',
    'Atama Problemi Amaç Fonksiyonu',
    FormulaCategory.operationsResearch,
    'min ΣᵢΣⱼ cᵢⱼxᵢⱼ',
    'Minimizes total assignment cost under one-to-one rules.',
    'Bire bir atama kuralları altında toplam maliyeti en aza indirir.',
    ['cᵢⱼ|assignment cost|atama maliyeti', 'xᵢⱼ|binary assignment|ikili atama'],
    'costs [[2,5],[4,1]]',
    'assign diagonal, total=3',
    'operations_research',
    'assignment,atama,cost,maliyet',
  ),
  _f(
    'cpm-es-ef',
    'CPM Earliest Start and Finish',
    'CPM En Erken Başlama ve Bitiş',
    FormulaCategory.operationsResearch,
    'ES = max(EF predecessors), EF = ES + duration',
    'Computes forward-pass activity times.',
    'İleri geçiş aktivite zamanlarını hesaplar.',
    [
      'ES|earliest start|en erken başlama',
      'EF|earliest finish|en erken bitiş',
      'duration|activity duration|aktivite süresi',
    ],
    'predecessor EF=4, duration=3',
    'ES=4, EF=7',
    'operations_research',
    'CPM,critical path,kritik yol',
  ),
  _f(
    'pert-expected-time',
    'PERT Expected Time',
    'PERT Beklenen Süre',
    FormulaCategory.operationsResearch,
    'tₑ = (a + 4m + b)/6',
    'Weights optimistic, most likely, and pessimistic times.',
    'İyimser, en olası ve kötümser süreleri ağırlıklandırır.',
    [
      'a|optimistic time|iyimser süre',
      'm|most likely time|en olası süre',
      'b|pessimistic time|kötümser süre',
    ],
    'a=2, m=5, b=8',
    'tₑ=5',
    'operations_research',
    'PERT,time,süre,project,proje',
  ),
  _f(
    'goal-deviations',
    'Goal Programming Deviations',
    'Hedef Programlama Sapmaları',
    FormulaCategory.operationsResearch,
    'fᵢ(x) + dᵢ⁻ - dᵢ⁺ = gᵢ',
    'Represents underachievement and overachievement of a goal.',
    'Bir hedefin altında ve üstünde kalma miktarlarını gösterir.',
    [
      'fᵢ(x)|goal expression|hedef ifadesi',
      'dᵢ⁻|underachievement|negatif sapma',
      'dᵢ⁺|overachievement|pozitif sapma',
      'gᵢ|target|hedef',
    ],
    'f(x)=90, g=100',
    'd⁻=10, d⁺=0',
    'operations_research',
    'goal programming,hedef programlama,deviation,sapma',
  ),
];

FormulaEntry _f(
  String id,
  String titleEn,
  String titleTr,
  FormulaCategory category,
  String formula,
  String descriptionEn,
  String descriptionTr,
  List<String> variableSpecs,
  String given,
  String result,
  String toolId,
  String tags, {
  FormulaDifficulty difficulty = FormulaDifficulty.basic,
}) {
  final tool = CalcademyToolRegistry.byId(toolId)!;
  final variables = variableSpecs
      .map((spec) {
        final parts = spec.split('|');
        return FormulaVariable(
          symbol: parts[0],
          nameEn: parts[1],
          nameTr: parts[2],
          descriptionEn: 'Represents ${parts[1]} in this formula.',
          descriptionTr: 'Bu formülde ${parts[2]} değerini temsil eder.',
        );
      })
      .toList(growable: false);
  return FormulaEntry(
    id: id,
    titleEn: titleEn,
    titleTr: titleTr,
    category: category,
    formulaText: formula,
    plainTextFormula: formula,
    descriptionEn: descriptionEn,
    descriptionTr: descriptionTr,
    variables: variables,
    examples: [
      FormulaExample(
        titleEn: 'Worked example',
        titleTr: 'Çözümlü örnek',
        givenValues: {'given': given},
        stepsEn: [
          'Substitute the given values into the formula.',
          'Simplify the expression carefully.',
        ],
        stepsTr: [
          'Verilen değerleri formülde yerine koyun.',
          'İfadeyi dikkatlice sadeleştirin.',
        ],
        result: result,
      ),
    ],
    tags: tags.split(','),
    relatedTools: [
      FormulaToolLink(
        toolId: tool.id,
        route: tool.route,
        labelEn: 'Open in ${tool.titleEn}',
        labelTr: '${tool.titleTr} aracında aç',
        supportedPrefill: tool.supportsPrefill,
        prefillSchema: tool.inputSchema,
      ),
    ],
    difficulty: difficulty,
  );
}
